site_name: Embedding.js Docs
site_url: http://embeddingjs.org
repo_url: https://github.com/beaucronin/embedding
site_author: Beau Cronin
site_dir: ../docs/docs
theme: flatly
google_analytics: ['UA-89921769-2', 'embeddingjs.org/docs']
pages:
  - Intro: 'index.md'
  - Docs:
    - Getting Started: 'getting-started.md'
    - Compatibility: 'compatibility.md'
    - Contributing: 'contributing.md'
    - Roadmap: 'roadmap.md'
  - API: 'api.md'

